version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: ${MYSQL_NAME:-todo-mysql}
    environment:
      MYSQL_DATABASE: ${DB_NAME:-mydb}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: ${REDIS_NAME:-todo-redis}
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password}
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/var/lib/redis
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  redis_data:
