version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: todo-mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: todo-redis
    command: redis-server --requirepass redis_password
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  redis_data:
